import type {
  Cluster,
  FightDetail,
  FirehoseEvent,
  Token,
  UnclusteredToken,
  Verdict,
} from "./types";

export const CONSTANTS = {
  totalTokensWatched: 384_127,
  tokensToday: 1_284,
  tokensYesterday: 1_142,
  clusteredPct: 67,
  activeClusters: 12,
  fightingNow: 4,
  pool24hBnb: 84.2,
  feesRedirectedTotal: 38.4,
  fightsResolved: 1_247,
  viewersLive: 47,
  embeddingModel: "text-embedding-3-small",
  visionModel: "clip-vit-base-patch32",
  threshold: 0.85,
  tokenMgrAddress: "0xF251F83e40a78868FcfA3FA4599Dad6494E46034",
};

function randSpark(seed: number, trend: "up" | "down" | "wobble"): number[] {
  const points: number[] = [];
  let v = 10;
  for (let i = 0; i < 12; i++) {
    const delta =
      trend === "up"
        ? -(1 + Math.sin(seed + i) * 0.8)
        : trend === "down"
        ? 1 + Math.cos(seed + i) * 0.8
        : Math.sin(seed + i * 2) * 1.2;
    v = Math.max(2, Math.min(17, v + delta));
    points.push(Number(v.toFixed(2)));
  }
  return points;
}

export const TOKENS: Token[] = [
  {
    id: "pepe2",
    symbol: "$PEPE2",
    slug: "pepe2.four.meme",
    ageHours: 14,
    holders: 847,
    top10Pct: 14,
    volLiqRatio: 4.2,
    liquidityBnb: 11.4,
    volume24hBnb: 47.88,
    bondingPct: 68,
    status: "IN_RING",
    spark: randSpark(1, "up"),
    clusterId: "frog",
    embedding: [0.12, 0.34],
  },
  {
    id: "pepe3",
    symbol: "$PEPE3",
    slug: "pepethethird.four.meme",
    ageHours: 9,
    holders: 521,
    top10Pct: 37,
    volLiqRatio: 4.6,
    liquidityBnb: 8.1,
    volume24hBnb: 37.26,
    bondingPct: 42,
    status: "IN_RING",
    spark: randSpark(2, "wobble"),
    clusterId: "frog",
    embedding: [0.14, 0.36],
  },
  {
    id: "pepe4",
    symbol: "$PEPE4",
    slug: "pepefour.four.meme",
    ageHours: 6,
    holders: 412,
    top10Pct: 28,
    volLiqRatio: 3.1,
    liquidityBnb: 5.6,
    volume24hBnb: 17.36,
    bondingPct: 33,
    status: "NEXT_UP",
    spark: randSpark(3, "up"),
    clusterId: "frog",
    embedding: [0.1, 0.32],
  },
  {
    id: "frogmaxi",
    symbol: "$FROGMAXI",
    slug: "frogmaxi.four.meme",
    ageHours: 3,
    holders: 203,
    top10Pct: 41,
    volLiqRatio: 5.8,
    liquidityBnb: 3.4,
    volume24hBnb: 19.72,
    bondingPct: 21,
    status: "NEXT_UP",
    spark: randSpark(4, "wobble"),
    clusterId: "frog",
    embedding: [0.16, 0.38],
  },
  {
    id: "ribbit",
    symbol: "$RIBBIT",
    slug: "ribbit.four.meme",
    ageHours: 2,
    holders: 98,
    top10Pct: 52,
    volLiqRatio: 2.2,
    liquidityBnb: 1.8,
    volume24hBnb: 3.96,
    bondingPct: 11,
    status: "QUEUED",
    spark: randSpark(5, "wobble"),
    clusterId: "frog",
    embedding: [0.13, 0.3],
  },
  {
    id: "pepelord",
    symbol: "$PEPELORD",
    slug: "pepelord.four.meme",
    ageHours: 1,
    holders: 67,
    top10Pct: 64,
    volLiqRatio: 1.9,
    liquidityBnb: 1.1,
    volume24hBnb: 2.09,
    bondingPct: 7,
    status: "QUEUED",
    spark: randSpark(6, "down"),
    clusterId: "frog",
    embedding: [0.15, 0.4],
  },
  {
    id: "pepeson",
    symbol: "$PEPESON",
    slug: "pepeson.four.meme",
    ageHours: 48,
    holders: 44,
    top10Pct: 81,
    volLiqRatio: 0.4,
    liquidityBnb: 0.6,
    volume24hBnb: 0.24,
    bondingPct: 4,
    status: "EATEN",
    spark: randSpark(7, "down"),
    clusterId: "frog",
    killedById: "pepe2",
    embedding: [0.11, 0.33],
  },
  {
    id: "pepocalypse",
    symbol: "$PEPOCALYPSE",
    slug: "pepocalypse.four.meme",
    ageHours: 72,
    holders: 29,
    top10Pct: 89,
    volLiqRatio: 0.1,
    liquidityBnb: 0.3,
    volume24hBnb: 0.03,
    bondingPct: 2,
    status: "EATEN",
    spark: randSpark(8, "down"),
    clusterId: "frog",
    killedById: "pepe3",
    embedding: [0.17, 0.37],
  },
];

export const CLUSTERS: Cluster[] = [
  {
    id: "frog",
    theme: "FROG",
    status: "FIGHTING",
    tokenCount: 8,
    overlapPct: 94,
    poolBnb: 6.33,
    fightId: "0047",
    fighters: ["$PEPE2", "$PEPE3"],
    members: [
      "IN_RING",
      "IN_RING",
      "NEXT_UP",
      "NEXT_UP",
      "QUEUED",
      "QUEUED",
      "EATEN",
      "EATEN",
    ],
    etaLabel: "47:23 LEFT",
    etaSeconds: 2843,
  },
  {
    id: "broccoli",
    theme: "BROCCOLI",
    status: "FIGHTING",
    tokenCount: 5,
    overlapPct: 89,
    poolBnb: 4.12,
    fightId: "0048",
    fighters: ["$BROCCOLI", "$BROC2"],
    members: ["IN_RING", "IN_RING", "NEXT_UP", "NEXT_UP", "QUEUED"],
    etaLabel: "22:08 LEFT",
    etaSeconds: 1328,
  },
  {
    id: "mubarak",
    theme: "MUBARAK",
    status: "FIGHTING",
    tokenCount: 6,
    overlapPct: 88,
    poolBnb: 2.88,
    fightId: "0049",
    fighters: ["$MUBARAK", "$MUBRK"],
    members: ["IN_RING", "IN_RING", "NEXT_UP", "NEXT_UP", "EATEN", "EATEN"],
    etaLabel: "1:04:12 LEFT",
    etaSeconds: 3852,
  },
  {
    id: "tst",
    theme: "TST",
    status: "RESOLVING",
    tokenCount: 11,
    overlapPct: 92,
    poolBnb: 8.94,
    fightId: "0046",
    fighters: ["$TST", "$TESTO"],
    members: [
      "IN_RING",
      "IN_RING",
      "NEXT_UP",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
    ],
    etaLabel: "00:47 LEFT",
    etaSeconds: 47,
  },
  {
    id: "cat",
    theme: "CAT",
    status: "QUEUED",
    tokenCount: 7,
    overlapPct: 87,
    poolBnb: 0,
    fighters: ["$CATCOIN", "$CATGOD"],
    members: ["QUEUED", "QUEUED", "QUEUED", "QUEUED", "QUEUED", "QUEUED", "QUEUED"],
    etaLabel: "STARTS IN 14M",
    etaSeconds: 840,
  },
  {
    id: "duck",
    theme: "DUCK",
    status: "NEW",
    tokenCount: 3,
    overlapPct: 90,
    poolBnb: 0,
    fighters: ["$QUACK", "$QUACKMAXI"],
    members: ["QUEUED", "QUEUED", "QUEUED"],
    etaLabel: "FORMING",
    etaSeconds: 0,
  },
  {
    id: "turbo",
    theme: "TURBO",
    status: "QUEUED",
    tokenCount: 9,
    overlapPct: 85,
    poolBnb: 0,
    fighters: ["$TURBOCOIN", "$TURBODOG"],
    members: [
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
    ],
    etaLabel: "STARTS IN 38M",
    etaSeconds: 2280,
  },
  {
    id: "wif",
    theme: "WIF",
    status: "QUEUED",
    tokenCount: 14,
    overlapPct: 91,
    poolBnb: 0,
    fighters: ["$WIF4", "$WIF5"],
    members: [
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "QUEUED",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
      "EATEN",
    ],
    etaLabel: "STARTS IN 2H 8M",
    etaSeconds: 7680,
  },
  {
    id: "moon",
    theme: "MOON",
    status: "QUEUED",
    tokenCount: 6,
    overlapPct: 86,
    poolBnb: 0,
    fighters: ["$MOONBOI", "$MOONDOG"],
    members: ["QUEUED", "QUEUED", "QUEUED", "QUEUED", "QUEUED", "QUEUED"],
    etaLabel: "STARTS IN 3H 22M",
    etaSeconds: 12120,
  },
  {
    id: "elon",
    theme: "ELON",
    status: "QUEUED",
    tokenCount: 18,
    overlapPct: 93,
    poolBnb: 0,
    fighters: ["$ELON3", "$ELON4"],
    members: Array(18).fill("QUEUED"),
    etaLabel: "STARTS IN 5H",
    etaSeconds: 18000,
  },
  {
    id: "ape",
    theme: "APE",
    status: "NEW",
    tokenCount: 3,
    overlapPct: 86,
    poolBnb: 0,
    fighters: ["$BIGAPE", "$APELORD"],
    members: ["QUEUED", "QUEUED", "QUEUED"],
    etaLabel: "FORMING",
    etaSeconds: 0,
  },
  {
    id: "doge",
    theme: "DOGE",
    status: "QUEUED",
    tokenCount: 22,
    overlapPct: 88,
    poolBnb: 0,
    fighters: ["$DOGE8", "$DOGE9"],
    members: Array(22).fill("QUEUED"),
    etaLabel: "STARTS IN 8H",
    etaSeconds: 28800,
  },
];

export const VERDICTS: Verdict[] = [
  {
    id: "v0046",
    fightId: "0046",
    clusterTheme: "WIF",
    winner: "$WIF2",
    losers: ["$WIF3"],
    resolvedAt: "02:14:21",
    feeRedirectBnb: 0.84,
    overlapPct: 91,
    daysLeft: 6,
    scoreA: 61.2,
    scoreB: 38.8,
    ipfsHash: "QmV2k...a9f3",
  },
  {
    id: "v0045",
    fightId: "0045",
    clusterTheme: "BROCCOLI",
    winner: "$BROCCOLI",
    losers: ["$BROCCOLI2"],
    resolvedAt: "01:52:10",
    feeRedirectBnb: 1.22,
    overlapPct: 89,
    daysLeft: 6,
    scoreA: 67.3,
    scoreB: 32.7,
    ipfsHash: "QmX4p...c2e8",
  },
  {
    id: "v0044",
    fightId: "0044",
    clusterTheme: "TST",
    winner: "$TST",
    losers: ["$TESTO", "$TSTR"],
    resolvedAt: "01:18:44",
    feeRedirectBnb: 2.41,
    overlapPct: 92,
    daysLeft: 6,
    scoreA: 54.8,
    scoreB: 45.2,
    ipfsHash: "QmR9n...f1b4",
  },
  {
    id: "v0043",
    fightId: "0043",
    clusterTheme: "MUBARAK",
    winner: "$MUBARAK",
    losers: ["$MUBRK"],
    resolvedAt: "00:47:12",
    feeRedirectBnb: 0.31,
    overlapPct: 88,
    daysLeft: 5,
    scoreA: 59.1,
    scoreB: 40.9,
    ipfsHash: "QmL8t...7d01",
  },
  {
    id: "v0042",
    fightId: "0042",
    clusterTheme: "FROG",
    winner: "$PEPE",
    losers: ["$PEPEBOT"],
    resolvedAt: "YESTERDAY 22:19",
    feeRedirectBnb: 0.97,
    overlapPct: 95,
    daysLeft: 5,
    scoreA: 72.4,
    scoreB: 27.6,
    ipfsHash: "QmA3q...88bc",
  },
  {
    id: "v0041",
    fightId: "0041",
    clusterTheme: "CAT",
    winner: "$CATTO",
    losers: ["$CATCOIN2", "$KITTY"],
    resolvedAt: "YESTERDAY 18:04",
    feeRedirectBnb: 1.58,
    overlapPct: 86,
    daysLeft: 5,
    scoreA: 48.9,
    scoreB: 51.1,
    ipfsHash: "QmK7w...01fa",
  },
  {
    id: "v0040",
    fightId: "0040",
    clusterTheme: "MOON",
    winner: "$MOONBOI",
    losers: ["$MOONLAD"],
    resolvedAt: "YESTERDAY 15:22",
    feeRedirectBnb: 0.42,
    overlapPct: 87,
    daysLeft: 5,
    scoreA: 55.6,
    scoreB: 44.4,
    ipfsHash: "QmZ1e...c4d8",
  },
  {
    id: "v0039",
    fightId: "0039",
    clusterTheme: "DOGE",
    winner: "$DOGE7",
    losers: ["$DOGELORD"],
    resolvedAt: "YESTERDAY 09:11",
    feeRedirectBnb: 0.68,
    overlapPct: 88,
    daysLeft: 4,
    scoreA: 63.8,
    scoreB: 36.2,
    ipfsHash: "QmB2u...5a72",
  },
];

export const FIREHOSE: FirehoseEvent[] = [
  { id: "f1", time: "02:14:47", type: "NEW", primary: "$FROGKING", secondary: "embedding..." },
  { id: "f2", time: "02:14:47", type: "MATCH", primary: "FROG cluster", accent: "91%" },
  { id: "f3", time: "02:14:33", type: "NEW", primary: "$MUBRAK", secondary: "embedding..." },
  { id: "f4", time: "02:14:33", type: "MATCH", primary: "MUBARAK cluster", accent: "88%" },
  {
    id: "f5",
    time: "02:14:21",
    type: "VERDICT",
    primary: "$WIF2 ate $WIF3",
    accent: "+0.84 BNB",
  },
  { id: "f6", time: "02:14:10", type: "NEW", primary: "$TURBODOG", secondary: "embedding..." },
  { id: "f7", time: "02:14:10", type: "UNCLUSTERED", primary: "unique vector" },
  { id: "f8", time: "02:13:58", type: "NEW", primary: "$PEPELORD", secondary: "embedding..." },
  { id: "f9", time: "02:13:58", type: "MATCH", primary: "FROG cluster", accent: "96%" },
  { id: "f10", time: "02:13:41", type: "NEW", primary: "$BROCOLI", secondary: "embedding..." },
  { id: "f11", time: "02:13:41", type: "MATCH", primary: "BROCCOLI cluster", accent: "89%" },
  {
    id: "f12",
    time: "02:13:22",
    type: "CLUSTER",
    primary: "BROCCOLI hit 5 members",
    accent: "FIGHT SCHEDULED",
  },
  { id: "f13", time: "02:13:10", type: "NEW", primary: "$CATGOD", secondary: "embedding..." },
  { id: "f14", time: "02:13:10", type: "MATCH", primary: "CAT cluster", accent: "87%" },
  { id: "f15", time: "02:12:58", type: "NEW", primary: "$TSTAR", secondary: "embedding..." },
  { id: "f16", time: "02:12:58", type: "MATCH", primary: "TST cluster", accent: "92%" },
  {
    id: "f17",
    time: "02:12:44",
    type: "VERDICT",
    primary: "$BROCCOLI ate $BROCCOLI2",
    accent: "+1.22 BNB",
  },
  { id: "f18", time: "02:12:30", type: "NEW", primary: "$DEGENBOT", secondary: "embedding..." },
  { id: "f19", time: "02:12:30", type: "UNCLUSTERED", primary: "unique vector" },
  { id: "f20", time: "02:12:18", type: "NEW", primary: "$PEPOCRAT", secondary: "embedding..." },
  { id: "f21", time: "02:12:18", type: "MATCH", primary: "FROG cluster", accent: "93%" },
  {
    id: "f22",
    time: "02:12:01",
    type: "CLUSTER",
    primary: "NEW cluster formed: DUCK",
    accent: "3 members",
  },
  { id: "f23", time: "02:11:44", type: "NEW", primary: "$QUACKMAXI", secondary: "embedding..." },
  { id: "f24", time: "02:11:44", type: "MATCH", primary: "DUCK cluster", accent: "90%" },
  { id: "f25", time: "02:11:30", type: "NEW", primary: "$TURBOCOIN", secondary: "embedding..." },
  { id: "f26", time: "02:11:30", type: "MATCH", primary: "TURBO cluster", accent: "85%" },
  {
    id: "f27",
    time: "02:11:14",
    type: "VERDICT",
    primary: "$TST ate $TESTO $TSTR",
    accent: "+2.41 BNB",
  },
  { id: "f28", time: "02:11:02", type: "NEW", primary: "$APELORD", secondary: "embedding..." },
  { id: "f29", time: "02:11:02", type: "MATCH", primary: "APE cluster", accent: "86%" },
  { id: "f30", time: "02:10:48", type: "NEW", primary: "$BNBMAXI88", secondary: "embedding..." },
  { id: "f31", time: "02:10:48", type: "UNCLUSTERED", primary: "unique vector" },
];

export const UNCLUSTERED_TOKENS: UnclusteredToken[] = [
  { symbol: "$TURBODOG", ageLabel: "14m" },
  { symbol: "$DEGENBOT", ageLabel: "22m" },
  { symbol: "$ZKLOOPER", ageLabel: "41m" },
  { symbol: "$BNBMAXI88", ageLabel: "1h" },
  { symbol: "$AGENTX", ageLabel: "1h" },
  { symbol: "$MOONBOI", ageLabel: "2h" },
  { symbol: "$GIGACHAD", ageLabel: "2h" },
  { symbol: "$SIGMAGRINDER", ageLabel: "3h" },
  { symbol: "$COPIUM", ageLabel: "3h" },
  { symbol: "$RETARDIO", ageLabel: "4h" },
  { symbol: "$VIBECHECK", ageLabel: "5h" },
  { symbol: "$NEOCON", ageLabel: "5h" },
];

export const FROG_FIGHT: FightDetail = {
  id: "0047",
  number: 47,
  clusterId: "frog",
  clusterTheme: "FROG CLUSTER",
  tokenA: TOKENS[0],
  tokenB: TOKENS[1],
  poolA: 3.42,
  poolB: 2.91,
  oddsA: 1.87,
  oddsB: 2.18,
  secondsLeft: 2843,
  projectedScoreA: 58.4,
  projectedScoreB: 41.6,
  overlapPct: 94,
  priorArt: [
    "both tokens deploy frog imagery",
    "both reference pepe lore in description",
    "launched 5h apart in same embedding cluster",
    "$PEPE3 description is near-identical copy of $PEPE2",
    "verdict: DERIVATIVE_DETECTED_",
  ],
  statBars: [
    { label: "HOLDERS", valueA: "847", valueB: "521", fillA: 62, fillB: 38 },
    { label: "TOP-10 CONC", valueA: "14%", valueB: "37%", fillA: 72, fillB: 28 },
    { label: "BUYERS 1H", valueA: "193", valueB: "278", fillA: 41, fillB: 59 },
    { label: "VOL ÷ LIQ", valueA: "4.2×", valueB: "4.6×", fillA: 48, fillB: 52 },
    { label: "X BUZZ", valueA: "VIRAL", valueB: "RAGE", fillA: 55, fillB: 45 },
  ],
  undercard: TOKENS,
};

export function getClusterById(id: string): Cluster | undefined {
  return CLUSTERS.find((c) => c.id === id);
}

export function getFightById(id: string): FightDetail | undefined {
  if (id === "0047") return FROG_FIGHT;
  const cluster = CLUSTERS.find((c) => c.fightId === id);
  if (!cluster) return undefined;
  return {
    ...FROG_FIGHT,
    id: cluster.fightId ?? id,
    number: Number(cluster.fightId ?? id),
    clusterId: cluster.id,
    clusterTheme: cluster.theme + " CLUSTER",
    tokenA: {
      ...TOKENS[0],
      symbol: cluster.fighters[0],
      slug: cluster.fighters[0].replace("$", "").toLowerCase() + ".four.meme",
    },
    tokenB: {
      ...TOKENS[1],
      symbol: cluster.fighters[1],
      slug: cluster.fighters[1].replace("$", "").toLowerCase() + ".four.meme",
    },
    secondsLeft: cluster.etaSeconds || 2843,
    overlapPct: cluster.overlapPct,
    priorArt: [
      `cluster theme: ${cluster.theme.toLowerCase()}`,
      `${cluster.tokenCount} tokens in bucket · ${cluster.overlapPct}% avg overlap`,
      "near-identical metadata detected by embedding",
      "verdict pending · DERIVATIVE_DETECTED_",
    ],
  };
}
